EGL: Fix compilation on Raspberry Pi.
Cross-compilation for the Raspberry Pi B+ fails with the following errors:

----8<----
../../../systems/egl/egl_system.c: In function 'InitEGL':
../../../systems/egl/egl_system.c:82:6: error: implicit declaration of function 'bcm_host_init' [-Werror=implicit-function-declaration]
      bcm_host_init();
      ^
../../../systems/egl/egl_system.c:126:6: error: implicit declaration of function 'graphics_get_display_size' [-Werror=implicit-function-declaration]
      graphics_get_display_size(0 /* LCD */, &egl->DisplayWidth, &egl->DisplayHeight);
      ^
---->8----

These functions are declared in `bcm_host.h`, at least on the Raspberry Pi
B+, so it must be included.